### ISSUE TITLE
Please take input from user

### ISSUE THREAD

**Issue by karthikphm** [iam-aniruddha/Python#1]
https://github.com/iam-aniruddha/Python/blob/9efdfb6395e96916cae2ab874acba4d1ac13a986/assignment/4_reverse_using_inbuilt_func.py#L18

**Comment by iam-aniruddha** [comment]
issue resolved - 
Now it will take input from user.
https://github.com/iam-aniruddha/Python/blob/main/assignment/4_reverse_using_inbuilt_func.py
