### ISSUE TITLE
Can it be done without returning the result of the decorated function, why is this needed??

### ISSUE THREAD

**Issue by karthikphm** [iam-aniruddha/Python#3]
https://github.com/iam-aniruddha/Python/blob/9efdfb6395e96916cae2ab874acba4d1ac13a986/assignment/decorator.py#L40

**Comment by iam-aniruddha** [comment]
Yes, it's possible to implement a decorator without explicitly returning the result of the decorated function. it depends on the requirements of our application, This is especially useful when the decorated function is expected to return a value that needs to be used elsewhere in our code.

When the original function is called inside the wrapper using func(*args, **kwargs), it returns a value, which is captured by result-
result = func( *args, **kwargs)
return result - Returns the result obtained from calling the original function, like in my case when I am using logger in any of the functions and if I am not returning the result then I am getting the none value as the result of that function.
The purpose of returning result is to maintain the behavior of the decorated function.
The return result statement in the wrapper function ensures that whatever value is returned by the original function is passed back to the caller of the decorated function. So, effectively, wrapper acts as an intermediary, allowing us to inject additional functionality (such as logging in this case) around the execution of the original function.
